### ISSUE TITLE
Torsigma limits

### ISSUE THREAD

**Issue by Rehamm** [JohannesBuchner/xars#1]
When using UXClumpy model in Xspec I found that the limits of Torsigma is from 0 to 84 but in the paper it is mentioned that it's limit is from 6 to 90. Should I change it?

**Comment by JohannesBuchner** [comment]
First, have a look at the top left panel of https://github.com/JohannesBuchner/xars/blob/master/doc/uxclumpy.rst
That geometry corresponds to a completely enshrouded AGN, with little azimuthal gradient.

I don't think it matters if it is 84 or 90, the paper was probably rounding it up. The highest geometry computed has indeed sigma=84°.

**Comment by Rehamm** [comment]
But what about the min limit because I have some sources fitted with UXClumpy and get so low value of Torsigma 10^-6.

**Comment by JohannesBuchner** [comment]
sigma=0 means the cloud population is not there, only the inner ring. This is shown in the right column in https://github.com/JohannesBuchner/xars/blob/master/doc/uxclumpy.rst. 

If that is the result, you discovered that in that source the obscurer is a smooth, high-column density structure, and not made of small clumps of intermediate column densities.

**Comment by Rehamm** [comment]
Thanks a lot for your help.

**Comment by JohannesBuchner** [comment]
I would also be happy to look over the paper once it is ready, if you would find that useful. Just send me an email.
Closing this issue for now.

**Comment by Rehamm** [comment]
Dear Johannes,

It would be my pleasure to look over my paper. Of course that will be very
useful for me. Thanks a lot.

Best regards,
Reham
