### ISSUE TITLE
AGN feedback and ICM

### ISSUE THREAD

**Issue by gabriel-fontinele** [JohannesBuchner/xars#2]
Hello, I currently work with galaxy clusters and AGN, more precisely the relationship between the AGN feedback and the intra-cluster medium, mainly with regard to the jets. I wanted to know if your work had anything to do with these aspects and how I could use it. Thank you in advance for your attention.

**Comment by JohannesBuchner** [comment]
xars can model photo-electric absorption, fluorescent emission lines and Compton scattering of cold, dense media. For AGN feedback in the central parsec, it has been used to predict the X-ray spectrum of Wada's radiative fountain model, using a previously made radiative-hydrodynamic simulation output box and something similar could perhaps be done for jets. For ionised media, as in Mpc-scale cluster hot gas, perhaps codes like cloudy or xstar (or apec) may be more appropriate.
